import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { createTaxonomyEntry, getTaxonomyEntries, type TaxonomyKind } from "@/lib/product-taxonomy";
import { DomainError } from "@/lib/errors";
import { assertSameOrigin, RequestSecurityError } from "@/lib/request-security";
const kindSchema = z.enum(["brands", "categories", "tags", "attributes", "reviews"]);
export async function GET(request: Request) { const user = await getCurrentUser(); if (!user || user.role !== "admin") return NextResponse.json({ error: "Admin access is required." }, { status: 401 }); const kind = kindSchema.safeParse(new URL(request.url).searchParams.get("kind")); if (!kind.success) return NextResponse.json({ error: "Choose a catalog section." }, { status: 400 }); try { return NextResponse.json({ entries: await getTaxonomyEntries(kind.data) }); } catch { return NextResponse.json({ error: "Catalog entries could not be loaded." }, { status: 500 }); } }
export async function POST(request: Request) { const user = await getCurrentUser(); if (!user || user.role !== "admin") return NextResponse.json({ error: "Admin access is required." }, { status: 401 }); try { assertSameOrigin(request); const body = z.object({ kind: kindSchema, name: z.string().trim().min(2).max(120), detail: z.string().trim().max(500).default("") }).parse(await request.json()); return NextResponse.json({ entry: await createTaxonomyEntry(body.kind as TaxonomyKind, body.name, body.detail, user.id) }, { status: 201 }); } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ error: "Complete the catalog fields." }, { status: 400 }); if (error instanceof DomainError) return NextResponse.json({ error: error.message }, { status: error.statusCode }); if (error instanceof RequestSecurityError) return NextResponse.json({ error: error.message }, { status: 403 }); return NextResponse.json({ error: "The catalog entry could not be saved." }, { status: 500 }); } }
