import type { Metadata } from "next";
import { KeyRound, LockKeyhole, SlidersHorizontal } from "lucide-react";
import { SiteSettingsForm } from "@/components/site-settings-form";
import { ThemeSettingsForm } from "@/components/theme-settings-form";
import { IntegrationSettingsForm } from "@/components/integration-settings-form";
import { getIntegrationSettings } from "@/lib/integrations";
import { getSiteSettings } from "@/lib/site-settings";
import { getThemeSettings } from "@/lib/theme-settings";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Settings" };

export default async function SettingsPage() {
  const [settings, integrations, theme] = await Promise.all([getSiteSettings(), getIntegrationSettings(), getThemeSettings()]);
  return <div className="content-width"><div className="page-topline"><div><span className="eyebrow">Workspace control</span><h1 className="page-title">Settings</h1><p className="page-subtitle">Manage company identity, native visual controls, and provider connections reused across operational workflows.</p></div></div><SiteSettingsForm settings={settings} /><ThemeSettingsForm settings={theme} /><IntegrationSettingsForm settings={integrations} /><div className="dashboard-grid section-spacer"><section className="panel"><div className="panel-header"><h2 className="panel-title">Configuration groups</h2><SlidersHorizontal size={17} color="#8b9995" /></div><div className="activity-list"><div className="activity-item"><span className="empty-icon" style={{ width: 32, height: 32 }}><KeyRound size={16} /></span><div className="activity-copy"><p><strong>Integrations</strong></p><small>Provider choices are stored centrally; credentials are encrypted and excluded from browser responses.</small></div></div><div className="activity-item"><span className="empty-icon" style={{ width: 32, height: 32 }}><LockKeyhole size={16} /></span><div className="activity-copy"><p><strong>Access & roles</strong></p><small>Capability-based permissions and audit history are part of the standalone model.</small></div></div></div></section><section className="insight-card" style={{ marginTop: 0 }}><span className="eyebrow">Fresh start</span><h3>No archived configuration was imported.</h3><p>All demo content is generated by the local seed. Provider calls remain disabled until credentials are intentionally configured.</p></section></div></div>;
}
