import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { KeyRound, LockKeyhole, SlidersHorizontal } from "lucide-react";
import { SiteSettingsForm } from "@/components/site-settings-form";
import { ThemeSettingsForm } from "@/components/theme-settings-form";
import { IntegrationSettingsForm } from "@/components/integration-settings-form";
import { getIntegrationSettings } from "@/lib/integrations";
import { getSiteSettings } from "@/lib/site-settings";
import { getThemeSettings } from "@/lib/theme-settings";
import { getCurrentUser, hasCapability } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Settings" };

export default async function SettingsPage() {
  const user = await getCurrentUser();
  if (!user || !hasCapability(user, "appearance.manage")) redirect("/admin");
  const canManageSettings = hasCapability(user, "settings.manage");
  const [theme, settings, integrations] = await Promise.all([
    getThemeSettings(),
    canManageSettings ? getSiteSettings() : Promise.resolve(null),
    canManageSettings ? getIntegrationSettings() : Promise.resolve(null),
  ]);
  return <div className="content-width"><div className="page-topline"><div><span className="eyebrow">Workspace control</span><h1 className="page-title">{canManageSettings ? "Settings" : "Appearance"}</h1><p className="page-subtitle">{canManageSettings ? "Manage company identity, native visual controls, and provider connections reused across operational workflows." : "Manage the native visual system and reusable template appearance for public and admin surfaces."}</p></div></div>{canManageSettings && settings ? <SiteSettingsForm settings={settings} /> : <div className="notice-banner"><LockKeyhole size={17} /><span><strong>Manager appearance access.</strong> You can adjust theme presets, layout, typography, colors, and reusable template styling. Company identity, integrations, credentials, and team access remain administrator-only.</span></div>}<ThemeSettingsForm settings={theme} />{canManageSettings && integrations ? <IntegrationSettingsForm settings={integrations} /> : null}{canManageSettings ? <div className="dashboard-grid section-spacer"><section className="panel"><div className="panel-header"><h2 className="panel-title">Configuration groups</h2><SlidersHorizontal size={17} color="#8b9995" /></div><div className="activity-list"><div className="activity-item"><span className="empty-icon" style={{ width: 32, height: 32 }}><KeyRound size={16} /></span><div className="activity-copy"><p><strong>Integrations</strong></p><small>Provider choices are stored centrally; credentials are encrypted and excluded from browser responses.</small></div></div><div className="activity-item"><span className="empty-icon" style={{ width: 32, height: 32 }}><LockKeyhole size={16} /></span><div className="activity-copy"><p><strong>Access & roles</strong></p><small>Capability-based permissions and audit history are part of the standalone model.</small></div></div></div></section><section className="insight-card" style={{ marginTop: 0 }}><span className="eyebrow">Fresh start</span><h3>No archived configuration was imported.</h3><p>All demo content is generated by the local seed. Provider calls remain disabled until credentials are intentionally configured.</p></section></div> : null}</div>;
}
