import { Mail, Smartphone, UsersRound } from "lucide-react";
import { StatusBadge } from "@/components/status-badge";
import { getRecentRegistrations } from "@/lib/data";
import { formatDateTime, formatMoney, initials } from "@/lib/format";

export default function AdminRegistrationsPage() {
  const registrations = getRecentRegistrations(40);
  return <div className="content-width"><div className="page-topline"><div><span className="eyebrow">Attendee operations</span><h1 className="page-title">Registrations</h1><p className="page-subtitle">Every synthetic registration, seat assignment, and delivery-ready contact in one view.</p></div><span className="status-badge status-active"><span className="status-dot" />{registrations.length} records</span></div><section className="panel">{registrations.length > 0 ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Attendee</th><th>Webinar</th><th>Seat</th><th>Payment</th><th>Contact</th><th>Registered</th></tr></thead><tbody>{registrations.map((registration) => <tr key={registration.id}><td><strong style={{ display: "flex", alignItems: "center", gap: 8 }}><span className="activity-avatar" style={{ width: 25, height: 25, flexBasis: 25 }}>{initials(registration.customerName)}</span>{registration.customerName}</strong><span className="muted" style={{ display: "block", marginLeft: 33, fontSize: 10 }}>{registration.customerEmail}</span></td><td style={{ maxWidth: 220, whiteSpace: "normal" }}>{registration.webinarTitle}</td><td>{registration.tierName}<br /><span className="muted">Seat {registration.seatNumber} · {formatMoney(registration.priceCents)}</span></td><td><StatusBadge status={registration.paymentStatus === "paid" ? "active" : "queued"} /></td><td><span className="row-meta"><Mail size={12} /> Email <Smartphone size={12} style={{ marginLeft: 4 }} /> {registration.customerPhone}</span></td><td className="muted">{formatDateTime(registration.createdAt)}</td></tr>)}</tbody></table></div> : <div className="empty-state"><div className="empty-icon"><UsersRound size={20} /></div><h3>No registrations yet</h3><p>Registrations created from the public session pages will appear here.</p></div>}</section></div>;
}
