"use client";

import { UserPlus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function CrmContactForm() {
  const router = useRouter(); const [form, setForm] = useState({ email: "", name: "", phone: "", company: "", lifecycleStage: "lead", marketingConsent: false, smsConsent: false }); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/admin/crm/contacts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "The contact could not be saved."); setForm({ email: "", name: "", phone: "", company: "", lifecycleStage: "lead", marketingConsent: false, smsConsent: false }); setMessage("Contact saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The contact could not be saved."); } finally { setSaving(false); } }
  return <form className="admin-form-card" onSubmit={submit}><h2>Add a contact</h2><div className="form-grid"><div className="form-row"><div className="field"><label htmlFor="crm-contact-name">Name</label><input id="crm-contact-name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Alex Morgan" required /></div><div className="field"><label htmlFor="crm-contact-email">Email</label><input id="crm-contact-email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="alex@example.com" required /></div></div><div className="form-row"><div className="field"><label htmlFor="crm-contact-phone">Phone</label><input id="crm-contact-phone" type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="(555) 010-0142" /></div><div className="field"><label htmlFor="crm-contact-company">Company</label><input id="crm-contact-company" value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} placeholder="Example Co." /></div></div><div className="form-row"><div className="field"><label htmlFor="crm-contact-stage">Lifecycle stage</label><select id="crm-contact-stage" value={form.lifecycleStage} onChange={(event) => setForm({ ...form, lifecycleStage: event.target.value })}><option value="lead">Lead</option><option value="attendee">Attendee</option><option value="customer">Customer</option><option value="inactive">Inactive</option></select></div><div><label className="check-field"><input type="checkbox" checked={form.marketingConsent} onChange={(event) => setForm({ ...form, marketingConsent: event.target.checked })} /><span>Marketing consent recorded</span></label><label className="check-field"><input type="checkbox" checked={form.smsConsent} onChange={(event) => setForm({ ...form, smsConsent: event.target.checked })} /><span>SMS consent recorded</span></label></div></div></div>{message ? <p className={message === "Contact saved." ? "form-success" : "form-error"} role="status">{message}</p> : null}<button className="button" type="submit" disabled={saving}><UserPlus size={15} />{saving ? "Saving…" : "Save contact"}</button></form>;
}
