"use client";

import { Workflow } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { EmailTemplateListItem } from "@/lib/types";

export function EmailSequenceForm({ templates }: { templates: EmailTemplateListItem[] }) {
  const router = useRouter();
  const [form, setForm] = useState({ name: "", slug: "", triggerKey: "", status: "draft", templateId: templates[0]?.id ?? "", delayMinutes: "0" });
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/admin/email/sequences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, delayMinutes: Number(form.delayMinutes) }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "The sequence could not be saved."); setMessage("Sequence saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The sequence could not be saved."); } finally { setSaving(false); } }
  return <form className="admin-form-card" onSubmit={submit}><h2>Create a sequence</h2><div className="form-grid"><div className="form-row"><div className="field"><label htmlFor="email-sequence-name">Name</label><input id="email-sequence-name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="New attendee follow-up" required /></div><div className="field"><label htmlFor="email-sequence-slug">Slug</label><input id="email-sequence-slug" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} placeholder="new-attendee-follow-up" /></div></div><div className="form-row"><div className="field"><label htmlFor="email-sequence-trigger">Trigger key</label><input id="email-sequence-trigger" value={form.triggerKey} onChange={(event) => setForm({ ...form, triggerKey: event.target.value })} placeholder="registration.created" required /></div><div className="field"><label htmlFor="email-sequence-status">Status</label><select id="email-sequence-status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select></div></div><div className="form-row"><div className="field"><label htmlFor="email-sequence-template">First template</label><select id="email-sequence-template" value={form.templateId} onChange={(event) => setForm({ ...form, templateId: event.target.value })} required><option value="">Choose a template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div><div className="field"><label htmlFor="email-sequence-delay">Delay before first step (minutes)</label><input id="email-sequence-delay" type="number" min="0" max="525600" value={form.delayMinutes} onChange={(event) => setForm({ ...form, delayMinutes: event.target.value })} required /></div></div></div>{message ? <p className={message === "Sequence saved." ? "form-success" : "form-error"} role="status">{message}</p> : null}<button className="button" type="submit" disabled={saving || templates.length === 0}><Workflow size={15} />{saving ? "Saving…" : "Save sequence"}</button></form>;
}
