"use client";

import { Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { EmailTemplateListItem, EmailTemplateRevisionView } from "@/lib/types";

export function EmailTemplateEditForm({ template, revisions }: { template: EmailTemplateListItem; revisions: EmailTemplateRevisionView[] }) {
  const router = useRouter();
  const [form, setForm] = useState({ name: template.name, triggerKey: template.triggerKey, messageType: template.messageType, subject: template.subject, preheader: template.preheader, htmlBody: template.htmlBody, textBody: template.textBody, status: template.status });
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  function update(name: string, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch(`/api/admin/email/templates/${encodeURIComponent(template.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "The template could not be updated."); setMessage("Saved as a new version."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The template could not be updated."); } finally { setSaving(false); } }
  return <details className="email-template-editor"><summary>Edit content · current version {template.version}</summary><form className="form-grid" onSubmit={submit}><div className="form-row"><div className="field"><label htmlFor={`template-name-${template.id}`}>Name</label><input id={`template-name-${template.id}`} value={form.name} onChange={(event) => update("name", event.target.value)} required /></div><div className="field"><label htmlFor={`template-trigger-${template.id}`}>Trigger key</label><input id={`template-trigger-${template.id}`} value={form.triggerKey} onChange={(event) => update("triggerKey", event.target.value)} required /></div></div><div className="form-row"><div className="field"><label htmlFor={`template-subject-${template.id}`}>Subject</label><input id={`template-subject-${template.id}`} value={form.subject} onChange={(event) => update("subject", event.target.value)} required /></div><div className="field"><label htmlFor={`template-status-${template.id}`}>Status</label><select id={`template-status-${template.id}`} value={form.status} onChange={(event) => update("status", event.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></div></div><div className="field"><label htmlFor={`template-preheader-${template.id}`}>Preview text</label><input id={`template-preheader-${template.id}`} value={form.preheader} onChange={(event) => update("preheader", event.target.value)} /></div><div className="form-row"><div className="field"><label htmlFor={`template-html-${template.id}`}>HTML content</label><textarea id={`template-html-${template.id}`} rows={7} value={form.htmlBody} onChange={(event) => update("htmlBody", event.target.value)} required /></div><div className="field"><label htmlFor={`template-text-${template.id}`}>Plain-text content</label><textarea id={`template-text-${template.id}`} rows={7} value={form.textBody} onChange={(event) => update("textBody", event.target.value)} required /></div></div><div className="form-actions"><button className="button button-small" type="submit" disabled={saving}><Save size={13} />{saving ? "Saving…" : "Save new version"}</button>{message ? <span className={message === "Saved as a new version." ? "form-success" : "form-error"}>{message}</span> : null}</div></form><details className="email-revision-history"><summary>Revision history ({revisions.length})</summary>{revisions.length > 0 ? <ul>{revisions.map((revision) => <li key={revision.id}><strong>Version {revision.version}</strong><span>{revision.subject}</span><small>{new Date(revision.createdAt).toLocaleString()}</small></li>)}</ul> : <p className="muted">No previous versions have been saved.</p>}</details></details>;
}
