import { randomUUID } from "node:crypto";
import { assertStandaloneDataset, getDb } from "@/lib/db";
import { DomainError } from "@/lib/errors";

export type TaxonomyKind = "brands" | "categories" | "tags" | "attributes" | "reviews";
export type TaxonomyEntry = { id: string; name: string; slug: string; detail: string; status: string };
function slugify(value: string): string { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80); }
export async function getTaxonomyEntries(kind: TaxonomyKind): Promise<TaxonomyEntry[]> { await assertStandaloneDataset(); if (kind === "brands") { const { rows } = await getDb().query<{ id: string; name: string; slug: string; description: string; status: string }>("SELECT id,name,slug,description,status FROM product_brands ORDER BY name"); return rows.map((row) => ({ id: row.id, name: row.name, slug: row.slug, detail: row.description, status: row.status })); } if (kind === "categories") { const { rows } = await getDb().query<{ id: string; name: string; slug: string; description: string; status: string }>("SELECT id,name,slug,description,status FROM product_categories ORDER BY name"); return rows.map((row) => ({ id: row.id, name: row.name, slug: row.slug, detail: row.description, status: row.status })); } if (kind === "tags") { const { rows } = await getDb().query<{ id: string; name: string; slug: string }>("SELECT id,name,slug FROM product_tags ORDER BY name"); return rows.map((row) => ({ id: row.id, name: row.name, slug: row.slug, detail: "Catalog tag", status: "active" })); } if (kind === "attributes") { const { rows } = await getDb().query<{ id: string; name: string; slug: string; display_type: string }>("SELECT id,name,slug,display_type FROM product_attributes ORDER BY name"); return rows.map((row) => ({ id: row.id, name: row.name, slug: row.slug, detail: `Display: ${row.display_type}`, status: "active" })); } const { rows } = await getDb().query<{ id: string; customer_name: string; rating: number; body: string; status: string }>("SELECT id,customer_name,rating,body,status FROM product_reviews ORDER BY created_at DESC"); return rows.map((row) => ({ id: row.id, name: `${row.customer_name} · ${"★".repeat(row.rating)}`, slug: row.id, detail: row.body, status: row.status })); }
export async function createTaxonomyEntry(kind: TaxonomyKind, name: string, detail: string, actorId: string): Promise<TaxonomyEntry> { await assertStandaloneDataset(); const cleanName = name.trim(); const slug = slugify(cleanName); if (cleanName.length < 2 || !slug) throw new DomainError("Enter a valid catalog name."); const id = `${kind.slice(0, -1)}-${randomUUID()}`; const now = new Date().toISOString(); if (kind === "brands") await getDb().query("INSERT INTO product_brands (id,name,slug,description,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$5)", [id, cleanName, slug, detail.trim(), now]); else if (kind === "categories") await getDb().query("INSERT INTO product_categories (id,name,slug,description,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$5)", [id, cleanName, slug, detail.trim(), now]); else if (kind === "tags") await getDb().query("INSERT INTO product_tags (id,name,slug,created_at) VALUES ($1,$2,$3,$4)", [id, cleanName, slug, now]); else if (kind === "attributes") await getDb().query("INSERT INTO product_attributes (id,name,slug,display_type,created_at,updated_at) VALUES ($1,$2,$3,'select',$4,$4)", [id, cleanName, slug, now]); else throw new DomainError("Reviews are created by customers and can be moderated here.", 409); await getDb().query("INSERT INTO audit_events (id,actor_id,event_type,entity_type,entity_id,metadata_json,created_at) VALUES ($1,$2,'catalog_taxonomy.created','catalog_taxonomy',$3,$4,$5)", [randomUUID(), actorId, id, JSON.stringify({ kind, synthetic: true }), now]); return { id, name: cleanName, slug, detail: detail.trim(), status: "active" }; }
