import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Clock3, MessageSquareText, ShieldCheck } from "lucide-react";
import { formatDateTime } from "@/lib/format";
import { getSmsOperationalState, getSmsOutbox, getSmsTemplates } from "@/lib/sms";
import { getCurrentUser, hasCapability } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "SMS notifications" };

function statusClass(status: string): string {
  if (status === "sent") return "active";
  if (status === "failed" || status === "suppressed") return "sold-out";
  return "queued";
}

export default async function SmsAdminPage() {
  const user = await getCurrentUser();
  if (!hasCapability(user, "messaging.manage")) redirect("/admin");
  const [templates, outbox] = await Promise.all([getSmsTemplates(), getSmsOutbox()]);
  const state = getSmsOperationalState();
  return <div className="content-width">
    <div className="page-topline"><div><span className="eyebrow">People & messaging</span><h1 className="page-title">SMS notifications.</h1><p className="page-subtitle">Manage consent-aware reminders, winner alerts, and durable text-message delivery jobs.</p></div><span className={`status-badge status-${state.enabled && state.configured ? "active" : "queued"}`}><span className="status-dot" />{state.enabled && state.configured ? `${state.provider} enabled` : "Provider-neutral"}</span></div>
    <div className="notice-banner"><ShieldCheck size={17} /><span><strong>Sending boundary.</strong> {state.enabled && state.configured ? `The ${state.provider} adapter is enabled.` : "Messages are queued safely, but no external SMS provider is contacted until SMS_ENABLED=true and a provider adapter is configured."} Consent, opt-out, and delivery status remain visible in the admin record.</span></div>
    <div className="stats-grid"><div className="stat-card"><span className="stat-label">Templates</span><div className="stat-value">{templates.length}</div><span className="stat-trend">Ready to edit</span></div><div className="stat-card"><span className="stat-label">Queued jobs</span><div className="stat-value">{outbox.filter((item) => item.status === "queued").length}</div><span className="stat-trend">Worker-ready</span></div><div className="stat-card"><span className="stat-label">Sent jobs</span><div className="stat-value">{outbox.filter((item) => item.status === "sent").length}</div><span className="stat-trend">Provider receipts</span></div><div className="stat-card"><span className="stat-label">Failed / suppressed</span><div className="stat-value">{outbox.filter((item) => item.status === "failed" || item.status === "suppressed").length}</div><span className="stat-trend stat-trend-muted">Needs review</span></div></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-header"><div><h2 className="panel-title">Message templates <span className="muted">({templates.length})</span></h2><span className="row-meta">Transactional SMS uses explicit consent</span></div><MessageSquareText size={17} color="#0f776e" /></div>{templates.length > 0 ? <div className="email-template-list">{templates.map((template) => <article className="email-template-row" key={template.id}><div><strong>{template.name}</strong><small>{template.triggerKey} · {template.messageType} · v{template.version}</small><p>{template.body}</p></div><span className={`status-badge status-${template.status === "active" ? "active" : "queued"}`}><span className="status-dot" />{template.status}</span></article>)}</div> : <div className="empty-state"><p>No SMS templates configured.</p></div>}</section><section className="panel"><div className="panel-header"><div><h2 className="panel-title">Operations checklist</h2><span className="row-meta">Production setup</span></div><Clock3 size={17} color="#8b9995" /></div><div className="activity-list"><div className="activity-item"><span className="empty-icon" style={{ width: 31, height: 31 }}>1</span><div className="activity-copy"><p><strong>Choose a provider</strong></p><small>Twilio adapter support is prepared; mock mode is used locally.</small></div></div><div className="activity-item"><span className="empty-icon" style={{ width: 31, height: 31 }}>2</span><div className="activity-copy"><p><strong>Verify a sender</strong></p><small>Configure a number or Messaging Service and complete required carrier registration.</small></div></div><div className="activity-item"><span className="empty-icon" style={{ width: 31, height: 31 }}>3</span><div className="activity-copy"><p><strong>Protect the worker</strong></p><small>Set SMS_WORKER_SECRET and schedule the internal process endpoint.</small></div></div></div></section></div>
    <section className="panel section-spacer"><div className="panel-header"><div><h2 className="panel-title">SMS outbox <span className="muted">({outbox.length})</span></h2><span className="row-meta">Reminder and winner jobs are idempotent</span></div><Clock3 size={17} color="#8b9995" /></div>{outbox.length > 0 ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Recipient</th><th>Template</th><th>Trigger</th><th>Status</th><th>Scheduled</th><th>Provider ID</th></tr></thead><tbody>{outbox.map((item) => <tr key={item.id}><td><strong>{item.recipientName || "Unnamed recipient"}</strong><span className="muted" style={{ display: "block" }}>{item.recipientPhone}</span></td><td>{item.templateName ?? "Template removed"}</td><td className="muted">{item.triggerKey}</td><td><span className={`status-badge status-${statusClass(item.status)}`}><span className="status-dot" />{item.status}</span></td><td className="muted">{formatDateTime(item.scheduledAt)}</td><td className="muted">{item.providerMessageId ?? "—"}</td></tr>)}</tbody></table></div> : <div className="empty-state"><p>No SMS jobs are queued yet. A consented registration creates confirmation and session-reminder jobs; a completed drawing creates a winner job.</p></div>}</section>
  </div>;
}
