import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { ProgressBar } from "@/components/progress-bar";
import { StatusBadge } from "@/components/status-badge";
import { getWebinars } from "@/lib/data";
import { formatDateTime, formatMoney } from "@/lib/format";
import type { WebinarStatus, WebinarVisibility } from "@/lib/types";

const statuses: Array<WebinarStatus | "all"> = ["all", "draft", "published", "sold_out", "completed"];
const visibilities: Array<WebinarVisibility | "all"> = ["all", "public", "private"];

export default async function AdminWebinarsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; visibility?: string }> }) {
  const params = await searchParams;
  const status = statuses.includes(params.status as WebinarStatus | "all") ? params.status as WebinarStatus | "all" : "all";
  const visibility = visibilities.includes(params.visibility as WebinarVisibility | "all") ? params.visibility as WebinarVisibility | "all" : "all";
  const query = params.q?.trim() ?? "";
  const webinars = await getWebinars(false, { query, status, visibility });
  return <div className="content-width"><div className="page-topline"><div><span className="eyebrow">Program management</span><h1 className="page-title">Webinars</h1><p className="page-subtitle">Prepare, publish, and monitor every session from one place.</p></div><Link href="/admin/webinars/new" className="button"><Plus size={16} /> Add new webinar</Link></div><section className="panel"><div className="admin-filter-bar"><form method="get" className="admin-filter-form"><div className="admin-search-field"><Search size={15} /><input name="q" defaultValue={query} placeholder="Search webinars or hosts" aria-label="Search webinars or hosts" /></div><select name="status" defaultValue={status} aria-label="Filter webinars by status">{statuses.map((value) => <option key={value} value={value}>{value === "all" ? "All statuses" : value.replace("_", " ")}</option>)}</select><select name="visibility" defaultValue={visibility} aria-label="Filter webinars by visibility">{visibilities.map((value) => <option key={value} value={value}>{value === "all" ? "All visibility" : value}</option>)}</select><button className="button button-small" type="submit">Filter</button>{query || status !== "all" || visibility !== "all" ? <Link href="/admin/webinars" className="panel-link">Clear</Link> : null}</form><span className="row-meta">{webinars.length} result{webinars.length === 1 ? "" : "s"}</span></div><div className="panel-header"><h2 className="panel-title">All sessions <span className="muted">({webinars.length})</span></h2><span className="eyebrow">Synthetic demo data</span></div>{webinars.length > 0 ? <div className="webinar-list">{webinars.map((webinar) => <Link href={`/admin/webinars/${webinar.id}`} className="webinar-row" key={webinar.id}><span className={`accent-bar ${webinar.accent === "coral" ? "coral" : webinar.accent === "gold" ? "gold" : ""}`} /><span><strong className="row-title">{webinar.title}</strong><span className="row-meta"><span>{formatDateTime(webinar.startsAt, webinar.timezone)}</span><span>{webinar.provider}</span><span>{webinar.visibility === "private" ? "Invite only" : "Public catalog"}</span></span></span><span className="row-metric"><strong>{webinar.sold}/{webinar.capacity}</strong><small>{formatMoney(webinar.revenueCents)} booked</small><ProgressBar value={webinar.sold} max={webinar.capacity} tone={webinar.accent === "coral" ? "coral" : webinar.accent === "gold" ? "gold" : "teal"} /></span><StatusBadge status={webinar.status} /></Link>)}</div> : <div className="empty-state"><p>No webinars match these filters.</p><Link href="/admin/webinars" className="panel-link" style={{ marginTop: 12 }}>Clear filters</Link></div>}</section></div>;
}
